### ISSUE TITLE
Funcionalidad de Filtros

### ISSUE THREAD

**Issue by Rombusevil** [MagmaPlayout/mp-ui-playout#8]
Desde el frontend el usuario va a poder elegir un piece al cual aplicarle uno o más filtros.
Cuando le aplique los filtros se va a crear un nuevo piece, no se va a modificar el original.
Para hacer esto, desde el frontend se debe grabar un nuevo registro en la tabla piece que tenga el filterId correspondiente y un nuevo path (podemos usar el nombre del original + YYYYMMDDHHMM) y después mandar un comando al core 
` APPLYFILTER {
    "from":"/carpeta/carpeta2/original.mlt",
    "to":"/carpeta/carpeta2/original201710071819.mlt",
    "filterId":1
}`

El core va a crear el archivo mlt con el filtro aplicado.

**Comment by Rombusevil** [comment]
Hago que el APPLYFILTER espere recibir el pieceId también:

`
APPLYFILTER { 
  "from":"/carpeta/carpeta2/original.mlt",
  "to":"/carpeta/carpeta2/original201710071819.mlt", 
  "filterId":1,
  "pieceId":1
}
`

**Comment by luism88** [comment]
**Quedaría así :** 
APPLYFILTER { "from":"/carpeta/carpeta2/original.mlt",  "piece": { id : 1,  path: "",  filterList : [] } }

 **- filterList es un array del tipo FilterModel**
export interface FilterModel{
id : number;
name : string;
description : string;
filterArgsList : Array<FilterArgsModel>;
}
 
export interface FilterArgsModel{
id : number;
filterId : number;
key : string;
description : string;
value : string;
}

**Comment by Rombusevil** [comment]
```
export interface PieceModel{
   id : number;
   name: string;
   path : string;
   resolution : string;
   frameRate: number;
   frameCount : number;
   duration : string,
   mediaId : number;
   media : MediaModel;
   sketch : SketchModel;
   tagList : Array<TagModel>;
   filterConfigList : Array<FilterConfigModel>;
}

export interface FilterConfigModel{
   id : number;
   pieceId : number;
   filterId : number;
   filterArgId : number;
   value : string;
   filterIndex : number;
   filter : FilterModel;
   piece : PieceModel;
   filterArg : FilterArgModel;
}
```
